const topicsData = {
    "categories": [
        {
            "name": "Vida",
            "topics": [
                "Vida",
                "Família",
                "Adoção",
                "Crianças",
                "Cuidados com Idosos",
                "Paternidade",
                "Maternidade",
                "Saúde",
                "Envelhecimento",
                "Coronavírus",
                "Covid-19",
                "Morte e Morrer",
                "Doença",
                "Relacionamentos",
                "Namoro",
                "Divórcio",
                "Amizade",
                "Amor",
                "Casamento"
            ]
        },
        {
            "name": "Autoaperfeiçoamento",
            "topics": [
                "Autoaperfeiçoamento",
                "Saúde Mental",
                "Ansiedade",
                "Aconselhamento",
                "Luto",
                "Lições de Vida",
                "Autoconsciência",
                "Produtividade",
                "Conselhos de Carreira",
                "Coaching",
                "Estabelecimento de Metas",
                "Rotinas Matinais",
                "Técnica Pomodoro",
                "Atenção Plena",
                "Meditação Guiada",
                "Diário",
                "Meditação",
                "Meditação Transcendental",
                "Yoga"
            ]
        },
        {
            "name": "Trabalho",
            "topics": [
                "Trabalho",
                "Negócios",
                "Empreendedorismo",
                "Freelancing",
                "Pequenas Empresas",
                "Startups",
                "Capital de Risco",
                "Marketing",
                "Publicidade",
                "Branding",
                "Marketing de Conteúdo",
                "Estratégia de Conteúdo",
                "Marketing Digital",
                "Liderança",
                "Engajamento de Funcionários",
                "Coaching de Liderança",
                "Desenvolvimento de Liderança",
                "Gerenciamento",
                "Reuniões"
            ]
        },
        {
            "name": "Tecnologia",
            "topics": [
                "Tecnologia",
                "Inteligência Artificial",
                "ChatGPT",
                "IA Conversacional",
                "Aprendizado Profundo",
                "Grandes Modelos de Linguagem",
                "Aprendizado de Máquina",
                "Blockchain",
                "Bitcoin",
                "Criptomoeda",
                "Finanças Descentralizadas",
                "Ethereum",
                "Nft",
                "Ciência de Dados",
                "Análise",
                "Engenharia de Dados",
                "Visualização de Dados",
                "Design de Banco de Dados",
                "Sql",
                "Desenvolvimento de Software",
                "Programação",
                "Desenvolvimento Android",
                "Codificação",
                "Flutter",
                "Engenharia Front-end",
                "Desenvolvimento iOS",
                "Linguagens de Programação",
                "Angular",
                "CSS",
                "HTML",
                "Java",
                "JavaScript",
                "DevOps",
                "AWS",
                "Databricks",
                "Docker",
                "Kubernetes",
                "Terraform"
            ]
        },
        {
            "name": "Mídia",
            "topics": [
                "Mídia",
                "Escrita",
                "Desafio de 30 Dias",
                "Resenhas de Livros",
                "Livros",
                "Não Ficção Criativa",
                "Diário",
                "Arte",
                "Quadrinhos",
                "Arte Contemporânea",
                "Desenho",
                "Belas Artes",
                "Arte Generativa",
                "Jogos",
                "Design de Jogos",
                "Desenvolvimento de Jogos",
                "Jogos Indie",
                "Metaverso",
                "Nintendo"
            ]
        },
        {
            "name": "Sociedade",
            "topics": [
                "Sociedade",
                "Economia",
                "Renda Básica",
                "Dívida",
                "Economia",
                "Inflação",
                "Mercado de Ações",
                "Educação",
                "Escolas Charter",
                "Reforma da Educação",
                "Ensino Superior",
                "Doutorado",
                "Escolas Públicas",
                "Igualdade",
                "Deficiência",
                "Discriminação",
                "Diversidade na Tecnologia",
                "Feminismo",
                "Inclusão"
            ]
        },
        {
            "name": "Cultura",
            "topics": [
                "Cultura",
                "Filosofia",
                "Ateísmo",
                "Epistemologia",
                "Ética",
                "Existencialismo",
                "Metafísica",
                "Religião",
                "Budismo",
                "Cristianismo",
                "Hinduísmo",
                "Islamismo",
                "Judaísmo",
                "Espiritualidade",
                "Astrologia",
                "Cura Energética",
                "Horóscopos",
                "Misticismo",
                "Reiki"
            ]
        },
        {
            "name": "Mundo",
            "topics": [
                "Mundo",
                "Cidades",
                "Abu Dhabi",
                "Amsterdã",
                "Atenas",
                "Bangcoc",
                "Barcelona",
                "Natureza",
                "Observação de Pássaros",
                "Camping",
                "Mudanças Climáticas",
                "Conservação",
                "Caminhadas",
                "Viagens",
                "Turismo",
                "Dicas de Viagem",
                "Escrita de Viagem",
                "Férias",
                "Vida na Van"
            ]
        }
    ]
};

export default topicsData;
